# version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - .:/app/backend
      - /app/backend/node_modules
    restart: always

  frontend:
    build:
      context: ./store
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
